services:
  Database:
    container_name: api-rest-demo_db
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: postgres

  Api:
    container_name: api-rest-demo_app
    image: api-rest-demo:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://Database:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - Database

